# Generated by Django 3.1.4 on 2020-12-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='image_ulr',
            new_name='image_url',
        ),
    ]
