# Generated by Django 3.1.4 on 2020-12-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expense_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='profile',
        ),
    ]
