# Generated by Django 3.1.4 on 2020-12-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
